# Generated by Django 3.2.3 on 2021-10-09 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Create date')),
                ('update_date', models.DateTimeField(auto_now=True, db_index=True, verbose_name='Update date')),
                ('title', models.CharField(blank=True, max_length=200)),
                ('content', models.TextField()),
            ],
            options={
                'abstract': False,
                'default_permissions': ('add', 'change', 'delete', 'view'),
            },
        ),
    ]
